'use strict';
'require baseclass';
'require uci';

/* Словарь панели byway.

   Устроен так же, как словарь консоли: ключ -- русская строка прямо из кода,
   перевод лежит рядом. Ни gettext, ни отдельного пакета luci-i18n здесь нет,
   и это выбор, а не упрощение: пакет перевода пришлось бы собирать и ставить
   отдельно, а без него панель осталась бы английской у того, кто перевода не
   ставил. С этим словарём пропущенная строка выводится по-русски -- то есть
   всегда осмысленно.

   Язык берётся из той же настройки, что и в консоли: byway.main.lang.
   Значит переключение одно на обе. */

var DICT = {
	en: {
		"(без имени)": "(unnamed)",
		"Служба": "Service",
		"Связь с VPN": "Link to the VPN",
		"Трафик через VPN": "Traffic through the VPN",
		"DNS": "DNS",
		"нет данных": "no data",
		"подключение": "connection",
		"сейчас": "now",
		"  ·  сейчас ": "  ·  now ",
		"ключ": "key",
		"(ключ не задан)": "(no key set)",
		"транспорт": "transport",
		"Адрес подписки указывается в поле выше.": "The subscription address goes in the field above.",
		"Список загружается…": "Loading the list…",
		"Ключей не пришло. Либо адрес неверен, либо ответ не успел прийти — вторая причина вероятнее, если подписка обычно работает.": "No keys arrived. Either the address is wrong, or the answer did not come in time — the second is more likely if the subscription usually works.",
		"Найдено ключей: ": "Keys found: ",
		". Нужный отмечается ниже:": ". Pick the one to use below:",
		" — byway такое не умеет": " — not supported by byway",
		"После выбора — кнопка «Применить» внизу страницы.": "Then press \"Save & Apply\" at the bottom of the page.",
		"Загрузить список ключей": "Load the list of keys",
		"Ключ не принят — работает прежняя настройка.": "Key not accepted — the previous setting is running.",
		"Применено, но byway есть что сказать:": "Applied, but byway has something to say:",
		"Применено": "Applied",
		"Часть трафика идёт через VPN, остальное напрямую.": "Part of the traffic goes through the VPN, the rest goes directly.",
		"Проверка": "Check",
		"Состояние": "Status",
		"Подключение": "Connection",
		"Перезапустить": "Restart",
		"Перезапуск уже идёт — дождитесь его.": "A restart is already running — wait for it.",
		"Перезапуск": "Restart",
		"Идёт перезапуск": "Restarting",
		"Перезапустить не удалось: ": "Restart failed: ",
		"Перезапуск идёт дольше, чем панель готова ждать. На роутере он продолжается — проверка обновится сама.": "The restart is taking longer than the panel will wait. It carries on at the router — the check will refresh itself.",
		"Проверить сейчас": "Check now",
		"Включить": "Enable",
		"Выключить — интернет останется, VPN не будет.": "Turn it off — the internet stays, the VPN does not.",
		"Способ подключения": "Connection method",
		"byway понимает vless, vmess, trojan, shadowsocks, socks, hysteria2 и wireguard. Автоматически — Xray-core замеряет задержку и ведёт трафик через самый быстрый живой ключ.": "byway understands vless, vmess, trojan, shadowsocks, socks, hysteria2 and wireguard. Automatically — Xray-core measures latency and routes traffic through the fastest live key.",
		"Один ключ": "One key",
		"Загрузка из подписки": "Loaded from a subscription",
		"Несколько, вручную": "Several, manual",
		"Несколько, автоматически": "Several, automatic",
		"Свой конфиг": "Custom config",
		"Ключ": "Key",
		"Ссылка целиком. Имя после решётки станет названием подключения.": "The whole link. The name after the hash becomes the connection name.",
		"Адрес подписки": "Subscription address",
		"Адрес https://…, по которому сервис отдаёт список ключей. Это не сам ключ.": "An https://… address where the service hands out a list of keys. Not a key itself.",
		"Ключ из подписки": "Key from the subscription",
		"Ключи": "Keys",
		"По одному на строку. Подписка заполняет их сама.": "One per line. A subscription fills them in by itself.",
		"Активный ключ": "Active key",
		"Ключи добавляются выше или загружаются из подписки.": "Keys are added above or loaded from a subscription.",
		"Конфиг аутбаунда": "Outbound config",
		"Кусок конфигурации Xray-core объектом: protocol, settings, при нужде streamSettings. Тег byway подставит сам.": "A piece of Xray-core config as an object: protocol, settings, streamSettings if needed. byway adds the tag itself.",
		"Название подключения": "Connection name",
		"Показывается в строке «Подключение» вверху страницы.": "Shown in the \"Connection\" line at the top of the page.",
		"свой конфиг": "custom config",
		"Если VPN не поднялся": "If the VPN does not come up",
		"Когда движок VPN на роутере не работает или перехват не лёг. Недоступный сервер при работающем движке сюда не относится: трафик и так уходит в движок и мимо VPN не идёт. «Пустить напрямую» — интернет работает, но то, что шло через VPN, идёт без него. «Не пускать» — это закрывается: в режиме «по спискам» — сайты из списков, в режиме «всё через VPN» — весь интернет. Доступ к роутеру остаётся.": "When the VPN engine on the router is not running or interception did not come up. An unreachable server with a running engine does not count: traffic goes into the engine anyway and does not bypass the VPN. \"Go direct\" — the internet keeps working, but what went through the VPN goes without it. \"Block\" — that traffic is cut: in by-lists mode, the listed sites; in everything-through-VPN mode, the whole internet. Access to the router stays.",
		"Пустить напрямую": "Go direct",
		"Не пускать": "Block",
		"Сеть": "Network",
		"Интерфейсы": "Interfaces",
		"Какие сети роутера пользуются VPN. Обычно одна — br-lan (домашняя); гостевая и другие появятся в списке, если заведены.": "Which of the router's networks use the VPN. Usually just br-lan (the home network); guest and other networks show up here once created.",
		"Сколько потоков в одно соединение. 0 — выключено, разумно 4–8. Помогает WebSocket, HTTPUpgrade и HTTP/2, где каждое соединение обходится дорого. XHTTP, gRPC, Hysteria2 и xtls-rprx-vision мультиплексируют сами — им второй слой мешает, и byway отключает mux; у WireGuard потока нет вовсе.": "How many streams per connection. 0 — off, 4–8 is sensible. Helps WebSocket, HTTPUpgrade and HTTP/2, where every connection is costly. XHTTP, gRPC, Hysteria2 and xtls-rprx-vision multiplex by themselves — a second layer gets in their way, and byway turns mux off; WireGuard has no stream at all.",
		"Сейчас не действует: у WireGuard потока нет, мультиплексировать нечего. ": "Not in effect now: WireGuard has no stream, there is nothing to multiplex. ",
		"Сейчас не действует: у транспорта ": "Not in effect right now: ",
		" своё мультиплексирование, byway отключает mux сам. ": " multiplexes on its own, so byway turns mux off. ",
		"DNS-сервер": "DNS server",
		"Шифрованный DoH: обычные запросы провайдер подменяет. Свой лучше вписывать адресом; именем — только вместе с полем «DNS для имени DoH-сервера».": "Encrypted DoH: the provider spoofs plain queries. Your own is best given by address; by name only together with the \"DNS for the DoH server name\" field.",
		"Google, запасной — 8.8.4.4": "Google, backup — 8.8.4.4",
		"Cloudflare, запасной — 1.0.0.1": "Cloudflare, backup — 1.0.0.1",
		"Quad9, режет вредоносные — 9.9.9.9": "Quad9, blocks malicious — 9.9.9.9",
		"Quad9, запасной — 149.112.112.112": "Quad9, backup — 149.112.112.112",
		"AdGuard, режет рекламу — 94.140.14.14": "AdGuard, blocks ads — 94.140.14.14",
		"AdGuard без фильтров — 94.140.14.140": "AdGuard, no filtering — 94.140.14.140",
		"Запасной DNS-сервер": "Backup DNS server",
		"Спрашивается, когда первый молчит. Берите ДРУГОГО оператора: у одного оператора оба адреса лежат в одной сети и падают вместе. Отключить — «без запасного» в списке.": "Asked when the first one stays silent. Pick a DIFFERENT operator: one operator's two addresses sit in the same network and fail together. To turn it off, pick \"no backup\".",
		"без запасного": "no backup",
		"DNS для имени DoH-сервера": "DNS for the DoH server name",
		"Нужен, только если DNS-сервер выше вписан именем (например dns.nextdns.io): у этого адреса спрашивается только имя DoH-сервера. При адресах — пусто.": "Needed only when the DNS server above is given by name (e.g. dns.nextdns.io): this address is asked only for the DoH server's name. Leave empty when the servers are addresses.",
		"Яндекс — 77.88.8.8": "Yandex — 77.88.8.8",
		"Путь к DNS-серверу": "Path to the DNS server",
		"Напрямую — быстрее, резолв не зависит от VPN. Через VPN — провайдер не видит и самих запросов. Домены из списка это не затрагивает: на них отвечают локально.": "Directly — faster, and resolution does not depend on the VPN. Through the VPN — the provider does not even see the queries. Domains from the list are unaffected: they are answered locally.",
		"Напрямую": "Directly",
		"Через VPN": "Through the VPN",
		"Пул подставных адресов": "Pool of stand-in addresses",
		"byway выдаёт домену из списка адрес отсюда, чтобы отличить его трафик от остального. Эти адреса нигде в интернете не существуют и наружу не уходят.": "byway hands a domain from the list an address out of this range, to tell its traffic apart from the rest. These addresses do not exist anywhere on the internet and never leave the router.",
		"Адрес резолвера byway": "Address of the byway resolver",
		"Куда dnsmasq пересылает запросы. Отдельный адрес нужен, чтобы не столкнуться с самим dnsmasq на том же порту.": "Where dnsmasq forwards queries. A separate address is needed so as not to collide with dnsmasq itself on the same port.",
		"Порт перехвата": "Interception port",
		"Порт прокси byway": "byway proxy port",
		"Через этот порт byway скачивает списки и обновления по VPN. Менять — только при столкновении с другой службой.": "byway uses this port to download lists and updates over the VPN. Change it only on a clash with another service.",
		"Отказ QUIC для сайтов через VPN": "Reject QUIC for sites through the VPN",
		"С ключами поверх TCP (vless, trojan, vmess) протокол QUIC внутри VPN зависает: приложение ждёт десятки секунд, прежде чем перейти на обычное соединение. С отказом сайт сразу открывается по TCP. С ключами hysteria2 и wireguard VPN сам идёт по UDP — там отказ не нужен.": "With keys over TCP (vless, trojan, vmess), QUIC inside the VPN stalls: an app waits for tens of seconds before it falls back to a regular connection. With the rejection, the site opens over TCP right away. With hysteria2 and wireguard keys the VPN itself runs over UDP — the rejection is not needed there.",
		"VPN для программ на роутере": "VPN for programs on the router",
		"Без неё программы на самом роутере (обновление zapret, свои скрипты) не достают до сайтов из списка и виснут до таймаута. Домашних устройств не касается; обновлениям byway не нужна.": "Without it, programs on the router itself (a zapret update, your own scripts) cannot reach the listed sites and hang until they time out. Home devices are not affected; byway's own updates do not need it.",
		"Порт для программ роутера": "Port for router programs",
		"Метка пакетов": "Packet mark",
		"Служебное значение, которым помечается перехваченный трафик. Менять только при столкновении с другой службой.": "A service value that marks intercepted traffic. Change it only on a collision with another service.",
		"Настройки не приняты — работают прежние.": "Settings rejected — the previous ones stay in effect.",
		"Что пускать через VPN": "What goes through the VPN",
		"По спискам — через VPN идёт только перечисленное ниже. Всё через VPN — весь трафик, включая загрузки и обновления.": "By lists — only what is listed below goes through the VPN. Everything through the VPN — all traffic, downloads and updates included.",
		"Режим": "Mode",
		"По спискам": "By lists",
		"Всё через VPN": "Everything through the VPN",
		".ru, .su и .рф — напрямую": ".ru, .su and .рф — directly",
		"Российские сайты мимо VPN. Выключать почти всегда ошибка.": "Russian sites bypass the VPN. Turning this off is almost always a mistake.",
		"Важно": "Important",
		"Через VPN пойдёт весь трафик: загрузки, видео, обновления. Если у VPN есть ограничение по объёму, оно кончится быстро.": "All traffic will go through the VPN: downloads, video, updates. If the VPN has a data cap, it will run out fast.",
		"Готовые списки": "Ready-made lists",
		"Работают вместе с вашими списками ниже, записи объединяются. Списки byway и itdoginfo-subnets приносят подсети, остальные только домены. Чужие списки никем не проверяются, а подсети в них бывают широкими — byway скажет насколько.": "Work alongside your own lists below, the entries are merged. The byway and itdoginfo-subnets lists bring subnets too, the rest are domains only. Third-party lists are checked by nobody, and their subnets can be wide — byway will say how wide.",
		"byway — список разработчика": "byway — the author’s list",
		"itdoginfo — закрытое для РФ": "itdoginfo — closed to Russia",
		"itdoginfo — заблокированное в РФ": "itdoginfo — blocked in Russia",
		"itdoginfo — подсети сервисов и хостеров": "itdoginfo — subnets of services and hosters",
		"Период автообновления": "Auto-update interval",
		"Например 12h, 2h37m, 1d, 90m; просто число — минуты. Не чаще 30m. Пусто — только по кнопке.": "For example 12h, 2h37m, 1d, 90m; a bare number means minutes. No more often than 30m. Empty — button only.",
		"Пишется как 12h, 2h37m, 1d или числом минут.": "Write it as 12h, 2h37m, 1d, or a number of minutes.",
		"Обновить готовые списки": "Update the ready-made lists",
		"Идёт загрузка…": "Loading…",
		"готово": "done",
		"применено": "applied",
		"скачано, но не применено — нажмите «Перезапустить» на вкладке «Основное»": "downloaded but not applied — press Restart on the Overview tab",
		"Загрузка идёт дольше, чем панель готова ждать. На роутере она продолжается — обновите страницу через минуту.": "The download is taking longer than the panel waits. It continues on the router — reload the page in a minute.",
		"Скачать сейчас": "Download now",
		"Домены (": "Domains (",
		"По одному на строку; строки с // или # — комментарии. Домен покрывает поддомены: example.com ловит и mail.example.com. Кириллица — в пуникоде (xn--…). Точнее: full: — только это имя, keyword: — часть имени, regexp: — регулярное выражение. Строки не по форме byway пропускает и называет при сборке.": "One per line; lines starting with // or # are comments. A domain covers its subdomains: example.com also catches mail.example.com. Cyrillic names go in punycode (xn--…). For precision: full: — this name only, keyword: — part of the name, regexp: — a regular expression. Lines in any other form are skipped, and byway names them when it builds the config.",
		"Подсети (": "Subnets (",
		"Диапазоны адресов, по одному на строку, в виде 1.2.3.0/24; одиночный адрес тоже годится. Только IPv4. Нужны для сервисов, которые работают не по именам, — например Telegram. Слишком широкие диапазоны вредны: они уводят в VPN чужой трафик и замедляют его.": "Address ranges, one per line, written as 1.2.3.0/24; a single address works too. IPv4 only. Needed for services that do not work by name — Telegram, for one. Ranges that are too wide do harm: they pull unrelated traffic into the VPN and slow it down.",
		"Направления": "Per-key routes",
		"Свой список для отдельного ключа: перечисленное в нём пойдёт не через основной ключ, а через выбранный. Имя направления — латиницей, оно же имя файла со списком.": "A separate list for a separate key: whatever is in it goes through the chosen key instead of the main one. The route name is in Latin letters and doubles as the list file name.",
		"Добавить направление": "Add a route",
		"Направление": "Route",
		"Направление «%s» будет удалено вместе со своим списком. Продолжить?": "Route \"%s\" will be removed together with its list. Continue?",
		"сначала добавьте ключи на «Основном»": "add keys on the Overview tab first",
		"Включено": "Enabled",
		"Записей": "Entries",
		"Список": "List",
		"Домены и подсети вперемешку, по одному на строку. Что похоже на адрес — пойдёт правилом по адресам, остальное по именам. Форма записи та же, что в общих списках выше, включая full:, keyword: и regexp:.": "Domains and subnets mixed, one per line. Whatever looks like an address goes into the address rule, the rest goes by name. The entry form is the same as in the lists above, full:, keyword: and regexp: included.",
		"Применение": "Applying",
		"Идёт пересборка и перезапуск": "Rebuilding and restarting",
		"Не применилось — работает прежняя настройка.": "Not applied — the previous setting is running.",
		"Обслуживание": "Maintenance",
		"Полное состояние": "Full status",
		"Сводка": "Summary",
		"Проверка окружения": "Environment check",
		"Проверить окружение": "Check the environment",
		"идёт проверка…": "checking…",
		"нет ответа": "no answer",
		"Отчёт для обращения": "Report for a support request",
		"Собрать отчёт": "Collect a report",
		"идёт сбор…": "collecting…",
		"Ответ": "Output",
		"Журнал состояния": "State log",
		"Пишется раз в пять минут и только когда что-то изменилось. Смена pid — это перезапуск службы. Здесь — последние десять записей, свежие сверху.": "Written every five minutes and only when something changed. A new pid means the service restarted. Shown here are the last ten entries, newest first.",
		"Записи": "Records",
		"пока пусто — значит ничего не менялось": "empty so far — which means nothing has changed",
		"Весь журнал": "Full log",
		"Открыть весь журнал": "Open the full log",
		"Закрыть": "Close",
		"Очистить": "Clear",
		"Очистить журнал": "Clear the log",
		"Записи об отвалах и перезапусках будут стёрты без возможности вернуть. Продолжить?": "The record of drops and restarts will be erased for good. Continue?",
		"Обновление": "Updates",
		"Установка идёт в фоне, ход виден ниже; служба перезапускается, туннель пропадает на несколько секунд.": "Installation runs in the background and its progress is shown below; the service restarts, and the tunnel drops for a few seconds.",
		"Проверка обновлений": "Update check",
		"Раз в 12–36 часов, в случайный момент, byway спрашивает GitHub, нет ли версии новее, и говорит об этом в сводке. Ничего не скачивает и не ставит.": "Every 12–36 hours, at a random moment, byway asks GitHub whether there is a newer version and says so in the summary. It downloads and installs nothing.",
		"Автоматическая установка обновлений": "Automatic update installation",
		"Выключено намеренно: обновление перезапускает службу, то есть на минуту отнимает туннель у всего дома. Включив, вы соглашаетесь, что это произойдёт в назначенный час ниже, по часам роутера, и не раньше чем через трое суток после выхода версии — важные ставятся сразу. Обновление идёт только внутри минорной версии, а если туннель не поднялся за две с половиной минуты, byway сам возвращает прежнюю. След утром — строка «ночью …» в сводке.": "Off on purpose: an update restarts the service, taking the tunnel away from the whole house for a minute. By turning it on you agree that this happens at the hour set below, by the router’s clock, and no sooner than three days after a release appears — important ones go in at once. Updates stay within the minor version, and if the tunnel does not come up within two and a half minutes byway puts the previous one back. The morning trace is the \"overnight …\" line in the summary.",
		"Час обновления": "Update hour",
		"По часам роутера. Его время и пояс — «Система → Система».": "By the router's clock. Its time and time zone are under System → System.",
		"Проверить": "Check",
		"Проверить обновление": "Check for an update",
		"Спросить не вышло — byway ничего не ответил.": "Could not ask — byway said nothing.",
		"Установка": "Installation",
		"Поставить обновление": "Install the update",
		"Поставить последний выпуск byway? Служба перезапустится, туннель пропадёт на несколько секунд.": "Install the latest byway release? The service will restart and the tunnel will drop for a few seconds.",
		"Ядро Xray": "Xray core",
		"Замена идёт в фоне, ход виден ниже. Если туннель на новом ядре не поднимется, byway вернёт прежнее.": "The swap runs in the background, progress is shown below. If the tunnel does not come up on the new core, byway puts the previous one back.",
		"Проверить обновление ядра": "Check for a core update",
		"Замена": "Swap",
		"Поставить проверенное ядро": "Install the tested core",
		"Поставить ядро Xray, проверенное с byway? Служба перезапустится; если на флеше нет места на второе ядро, туннеля не будет около минуты.": "Install the Xray core tested with byway? The service will restart; if flash has no room for a second core, the tunnel will be down for about a minute.",
		"Другая версия": "Another version",
		"Номер выпуска Xray-core, например 26.9.30. Список выпусков — на GitHub XTLS/Xray-core.": "An Xray-core release number, for example 26.9.30. Releases are listed on GitHub at XTLS/Xray-core.",
		"нужен номер вида 26.9.30": "a number like 26.9.30 is needed",
		"Поставить эту версию": "Install this version",
		"Поставить Xray-core %s? Служба перезапустится; если на флеше нет места на второе ядро, туннеля не будет около минуты.": "Install Xray-core %s? The service will restart; if flash has no room for a second core, the tunnel will be down for about a minute.",
		"Экспорт настроек": "Export settings",
		"Все настройки и списки одним текстом. Такой текст переносят на другой роутер, сохраняют перед опытами или прикладывают к вопросу о поломке.": "All settings and lists as one text. Use it to move settings to another router, keep a copy before experimenting, or attach to a bug report.",
		"Без ключа от VPN": "Without the VPN key",
		"Со снятой галочкой в текст попадёт ключ, и показывать такой файл нельзя никому.": "With the box cleared the key goes into the text, and such a file must not be shown to anyone.",
		"Выгрузка": "Export",
		"здесь появится выгрузка": "the export will appear here",
		"Показать": "Show",
		"не получилось": "did not work",
		"Скачать файлом": "Download as a file",
		"Сначала нужно нажать «Показать».": "Press \"Show\" first.",
		"Галочка «Без ключа» изменилась после сбора — нажмите «Показать» ещё раз, иначе в файл уйдёт не то, что вы видите.": "The \"without the key\" box changed after the export was made — press \"Show\" again, otherwise the file will not hold what you see.",
		"Импорт настроек": "Import settings",
		"Списки будут заменены целиком. Прежние сохраняются в /etc/byway/before-import/ — если новая настройка не соберётся, byway вернёт всё как было.": "The lists will be replaced whole. The previous ones are kept in /etc/byway/before-import/ — if the new setting does not build, byway puts everything back.",
		"выгрузка целиком, начиная с # byway export": "the whole export, starting with # byway export",
		"Оставить нынешний ключ": "Keep the current key",
		"Принять всё, кроме подключения к VPN. По умолчанию ключ берётся из выгрузки — если он в ней есть.": "Accept everything except the VPN connection. By default the key is taken from the export — if it has one.",
		"Принять": "Import",
		"Это не выгрузка byway: в первой строке должно быть «# byway export».": "This is not a byway export: the first line must be \"# byway export\".",
		"Настройки и списки будут заменены содержимым выгрузки. Продолжить?": "The settings and lists will be replaced by the contents of the export. Continue?",
		"идёт применение…": "applying…",
		"Не принято — осталось как было.": "Not imported — everything stayed as it was.",
		"Принято и применено": "Imported and applied",
		"Приём идёт дольше, чем панель готова ждать. На роутере он продолжается — откройте вкладку заново через минуту и посмотрите «Полное состояние».": "The import is taking longer than the panel waits. It continues on the router — reopen the tab in a minute and look at \"Full state\".",
		"Чем пользуются": "What is actually used",
		"Какие записи списков правда используются — пригодится, когда список чистят. Данные не покидают роутер.": "Which list entries are actually used — handy when cleaning up the lists. The data never leaves the router.",
		"Сбор статистики": "Statistics collection",
		"Статистика": "Statistics",
		"Не собирается: в режиме «Всё через VPN» туда попадает каждый открытый домен.": "Not collected: in \"Everything through the VPN\" mode every domain you open lands there.",
		"загружается…": "loading…",
		"пока пусто": "empty so far",
		"Соединения к подсетям идут по адресам и к домену не привязываются — они одной строкой «(по IP)».": "Connections to subnets go by address and are not tied to a domain — they show as a single \"(by IP)\" line.",
		"Очистить статистику": "Clear the statistics",
		"Накопленная статистика будет стёрта без возможности вернуть. Продолжить?": "The collected statistics will be erased for good. Continue?",
		"Дополнительное": "Advanced",
		"Значения по умолчанию подобраны и работают. Менять их стоит, только если понятна причина.": "The defaults were chosen and they work. Changing them makes sense only when the reason is clear.",
		"Подробность журнала": "Log detail",
		"Подробные уровни имеет смысл включать на время разбирательства: журнал живёт в памяти и при большом трафике быстро вытесняет сам себя. Начиная с «каждого соединения» в него попадают ещё и адреса, к которым обращаются из сети.": "The detailed levels are worth switching on for the length of an investigation: the log lives in memory and at high traffic quickly pushes itself out. From \"every connection\" upwards it also records the addresses being reached from the network.",
		"ничего": "nothing",
		"только ошибки": "errors only",
		"ошибки и предупреждения": "errors and warnings",
		"каждое соединение": "every connection",
		"всё подряд": "everything",
		"Интервал проверки ключей": "Key check interval",
		"Только для режима автовыбора: с каким шагом Xray-core проверяет задержку до каждого ключа. Чаще — быстрее заметит отвал, но больше лишнего трафика.": "For the automatic mode only: how often Xray-core checks the latency to every key. More often means an outage is noticed sooner, but there is more idle traffic.",
		"Язык": "Language",
		"Язык панели и вывода команды byway в консоли. Английский словарь byway скачивает с GitHub при переключении.": "Language of the panel and of the byway console output. byway downloads the English dictionary from GitHub when switching.",
		"Путь к ядру Xray": "Xray core path",
		"Путь вписывает byway engine при замене ядра. Пусто — ядро из пакета.": "The path is set by byway engine when it replaces the core. Empty means the packaged core.",
		"Восстановление перехвата": "Interception auto-restore",
		"Раз в пять минут byway проверяет, на месте ли его правила в файрволе, и возвращает их, если их сняли (чужой скрипт, обновление firewall4, другая служба). Снятые вручную командой byway plumb off не возвращаются до перезагрузки.": "Every five minutes byway checks that its firewall rules are in place and puts them back if something removed them (another script, a firewall4 upgrade, another service). Rules taken down by hand with byway plumb off are left alone until reboot.",
		"Словарь не установлен — язык остался прежним.": "The dictionary was not installed — the language stays the same.",
		"Панель byway обновлена до %s, а браузер показывает прежнюю (%s) из кэша. Обновить страницу без кэша: Ctrl+Shift+R; на телефоне — очистить кэш браузера.": "The byway panel was updated to %s, but the browser shows the previous one (%s) from its cache. Reload the page without the cache: Ctrl+Shift+R; on a phone, clear the browser cache.",
		"Очистить не удалось: ": "Could not clear: ",
		"запуск…": "starting…",
		"Основное": "Overview",
		"Маршруты": "Routes",
	}
};

return baseclass.extend({
	dict: DICT,

	/* uci.load('byway') делает каждая вкладка в load(), поэтому здесь
	   значение уже есть. Если вдруг нет -- вернём русский, а не пустоту. */
	lang: function () {
		try { return uci.get('byway', 'main', 'lang') || 'ru'; }
		catch (e) { return 'ru'; }
	},

	/* Названия вкладок приходят из menu.json и рисуются ДО того, как
	   вкладка загрузится: их LuCI берёт с сервера и переводит своим
	   механизмом .po, которого у byway нет. Поэтому переписываем их в
	   разметке -- по своим же ссылкам и только их.

	   Если разметка окажется другой, ничего не произойдёт: элементов не
	   найдётся, названия останутся русскими. Это и есть цена приёма --
	   он не может сломать страницу, но может однажды перестать работать. */
	tabs: function () {
		if (this.lang() === 'ru') return;
		var self = this;
		document.querySelectorAll('a[href*="/services/byway/"]')
			.forEach(function (a) {
				var v = self.tr(a.textContent.trim());
				if (v !== a.textContent.trim()) a.textContent = v;
			});
	},

	tr: function (s) {
		var l = this.lang();
		if (l === 'ru') return s;
		var d = DICT[l];
		return (d && d[s]) || s;
	}
});
